# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# Ubuntu 18.04
dist: xenial

language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "malvinsug"
    token:
      secure: "2203f7c78688b2e977f7dc37021db3bab626260c"



before_install:
  # Get author name for the test report
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=crewmeister

after_success:
  # the following commands build the UpdateSheet.java file and report a successful test.
  - mvn compile
  - mvn exec:java -Dexec.mainClass="api.UpdateSheet" -Dexec.args="$AUTHOR_NAME SUCCESSFUL"

after_failure:
  # the following commands build the UpdateSheet.java file and report a failed test.
  - mvn compile
  - mvn exec:java -Dexec.mainClass="api.UpdateSheet" -Dexec.args="$AUTHOR_NAME FAILED"